batdc/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  
  devise_scope :user do
    root to: 'lists#index'    
    get 'access_denied' => 'users/registrations#access_denied', as: :access_denied
  end

  resources :users, :except => [:new, :create] do
    member do
      patch :authorize
    end
  end
 
  resources :contacts do
    collection do
      get :email
    end
  end

  resources :schools do
    member do
      patch :add_preferred
      patch :add_membership
      patch :del_membership
    end
  end
  resources :events do
    member do
      patch :add_attendee
      get :email
      get :export
    end
  end

  resources :attendees, only: [:destroy]
  resources :preferred_contacts, only: [:destroy]

  get 'lists/index' => 'lists#index'
  get 'lists/membership' => 'lists#membership'
end

batdc/app/models/contact.rb
class Contact < ActiveRecord::Base
  include ActiveModel::Serialization

  belongs_to :school
  has_one :preferred_contact
  has_many :attendees
  has_many :events, through: :attendees

  scope :role, -> (role) { where role: role }

  scope :status, -> (status) { where status: status }
  scope :subject, -> (subject) { where subject_area: subject }
  scope :search, -> (term) {
    t = "%#{term}%"
    pred = "last like ? "
    pred += "or first like ? "
    pred += "or role like ? "
    pred += "or title like ? "
    pred += "or email_primary like ?"
    pred += "or email_secondary like ? "
    pred += "or subject_area like ? "
    where(pred, t, t, t, t, t, t, t)
  }
  
  scope :at_school, -> (at_school) { where school_id: at_school if
    at_school and at_school.length > 0 }
  
  scope :in_region, -> (region) {
    where school: School.region(region)
  }

  scope :at_member, -> {
    where school: School.current_member
  }

  scope :at_non_member, -> {
    where school: School.non_member
  }
  
  scope :is_function, -> (function) { where role:
    Function.roles_by_function(function) }  

  scope :teaches, -> (grades) { 
    terms = []
    grades.each do |g|
      terms << "#{g} is true"
    end
    where( terms.join(" or ") )
  }

  scope :is_preferred, -> {
    where id: PreferredContact.select(:contact_id)
  }

  def sort_name
    fn = "#{self.first}"
    fn = 'BLANK' if fn.blank?

    ln = "#{self.last}"
    ln = 'BLANK' if ln.blank?

    sn = "#{ln}, #{fn}"
  end

  def full_name
    fn = "#{self.first} #{self.last}"
    fn = 'BLANK' if fn.blank?
    fn
  end

  def role_and_name
    rn = full_name
    rn += " - #{role}" if role
    rn
  end

  def email
    return email_secondary unless email_primary
    return email_primary
  end

  def subject
    return other_subject unless subject_area
    return subject_area
  end

  def school_name
    return school.official_name if school
    return "NOT SPECIFIED"
  end

  # def self.as_csv(options={})
  #   CSV.generate(options) do |csv|
  #     substitute = {
  #       school_id: :school
  #     }
  #     #csv << column_names
      
  #     exp_cols = []
  #     column_names.each do |c|
  #       if substitute.has_key? c
  #         exp_cols << substitute[c]
  #       else
  #         exp_cols << c
  #       end
  #     end
      
  #     csv << exp_cols

  #     all.each do |item|
  #       col_vals = []
  #       col_vals << item.attributes.values_at(*column_names)
  #       csv << col_vals
  #     end
  #   end
  # end

  def grade_field_label(f)
    labels = {}
    labels[:gPK] = "Pre K"
    labels[:gK] = "Kindergarden"
    labels[:g01] = "Grade 1"
    labels[:g02] = "Grade 2"
    labels[:g03] = "Grade 3"
    labels[:g04] = "Grade 4"
    labels[:g05] = "Grade 5"
    labels[:g06] = "Grade 6"
    labels[:g07] = "Grade 7"
    labels[:g08] = "Grade 8"
    labels[:g09] = "Grade 9"
    labels[:g10] = "Grade 10"
    labels[:g11] = "Grade 11"
    labels[:g12] = "Grade 12"

    labels[f]
  end

  def grades_taught
    grades = []
    grades << "Pre K" if self.gPK
    grades << "Kindergarden" if self.gK
    grades << "Grade 1" if self.g01
    grades << "Grade 2" if self.g02
    grades << "Grade 3" if self.g03
    grades << "Grade 4" if self.g04
    grades << "Grade 5" if self.g05
    grades << "Grade 6" if self.g06
    grades << "Grade 7" if self.g07
    grades << "Grade 8" if self.g08
    grades << "Grade 9" if self.g09
    grades << "Grade 10" if self.g10
    grades << "Grade 11" if self.g11
    grades << "Grade 12" if self.g12
    grades
  end
end

batdc/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  load_and_authorize_resource except: [:create]
  
  before_filter :check_for_mobile, :only => [:index]

  def index
    if params[:at_member].blank?
      @contacts = Contact.all
    elsif params[:at_member] == "false"
      @contacts = @contacts.at_non_member
    else
      @contacts = @contacts.at_member
    end

    @contacts = @contacts.status('Active') unless params[:show_inactive]
    @contacts = @contacts.search(params[:search]) unless params[:search].blank?
    @contacts = @contacts.in_region(params[:in_region]) unless params[:in_region].blank?
    @contacts = @contacts.at_school(params[:at_school]) unless params[:at_school].blank?
    @contacts = @contacts.is_function(params[:is_function]) unless
    params[:is_function].blank? 
    @contacts = @contacts.role(params[:role]) unless params[:role].blank?
    @contacts = @contacts.teaches(params[:teaches]) unless params[:teaches].blank?
    @contacts = @contacts.is_preferred unless
    params[:is_preferred].blank?
    @contacts = @contacts.subject(params[:subject]) unless params[:subject].blank?
    @contacts = @contacts.order(:last, :first)
    
    respond_to do | format |
      format.html { @contacts = @contacts.paginate(:page =>
      params[:page]) unless params[:mobile] }
      format.csv { render csv: @contacts, filename: 'contacts',
      each_serializer: ContactSerializer, only: [ :last, :first,
      :role, :title, :work_phone], add_methods: [:school_name, :email,
      :subject] } 
      format.json { render json: @contacts, each_serializer:
      ContactSerializer }
    end
  end

  def create
    authorize! :create, Contact
    if params[:commit] == "Cancel"
      redirect_to Contact
    else
      @contact = Contact.create(contact_params)
      redirect_to @contact
    end
  end

  def update
    if params[:commit] == "Cancel"
      redirect_to @contact
    else
      if @contact.update(contact_params)
        redirect_to @contact
      else
        render 'edit'
      end
    end
  end

  def email
     if not params.has_key? :at_member
      @contacts = Contact.all
    elsif params[:at_member]
      @contacts = @contacts.at_member
    else
      @contacts = @contacts.at_member
    end

    @contacts = @contacts.status('Active')
    @contacts = @contacts.search(params[:search]) unless params[:search].blank?
    @contacts = @contacts.in_region(params[:in_region]) unless params[:in_region].blank?
    @contacts = @contacts.at_school(params[:at_school]) unless params[:at_school].blank?
    @contacts = @contacts.is_function(params[:is_function]) unless
    params[:is_function].blank? 
    @contacts = @contacts.role(params[:role]) unless params[:role].blank?
    @contacts = @contacts.teaches(params[:teaches]) unless params[:teaches].blank?
    @contacts = @contacts.is_preferred unless params[:is_preferred].blank?
    @contacts = @contacts.order(:last, :first)
  end

  def destroy
    if @contact.attendees.length > 0
      flash[:alert] = "Remove event attendance before deleting:
    #{@contact.full_name}"
      redirect_to @contact
    elsif @contact.preferred_contact
      flash[:alert] = "#{@contact.full_name} is a preferred contact at
    #{@contact.preferred_contact.school.name}"
      redirect_to @contact
    else
      @contact.destroy
      flash[:notice] = "Deleted Contact: #{@contact.full_name}"
      redirect_to Contact
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:last, :first, :title, :role, 
  :eventbrite_id, :school_id, :email_primary, :email_secondary,
  :work_phone, :subject_area, :other_subject, :gPK, :gK, :g01, :g02, :g03,
  :g04, :g05, :g06, :g07, :g08, :g09, :g10, :g11, :g12, :notes, :status)
  end

end

batdc/app/views/contacts/_contact.html.erb
<div class="row">
    <%= f.label :status, class: "col-xs-2 col-sm-2"%>
    <%= f.select :status, ['Active', 'Inactive'], class: "col-xs-4 col-sm-2"%>
</div>

<div class="row">
    <%= f.label :last_name, class: "col-xs-2 col-sm-2" %>
    <%= f.text_field :last, class: "col-xs-4 col-sm-4" %>
    
    <%= f.label :first_name, class: "col-xs-2 col-sm-2"%>
    <%= f.text_field :first, class: "col-xs-4 col-sm-4"%>
</div>

<div class="row">
    <%= f.label :title, class: "col-sm-2"%>
    <%= f.text_field :title, class: "col-sm-4" %>

    <%= f.label :role, class: "col-sm-2"%>
    <%= f.collection_select(:role, Function.all, :role, :role, class: "col-sm-4") %>
</div>

<div class="row">
    <%= f.label :eventbrite_id, class: "col-sm-2" %>
    <%= f.number_field :eventbrite_id, class: "col-sm-4" %>

    <%= f.label :school, class: "col-sm-2"%>
    <%= collection_select(:contact, :school_id, School.all.order(:name), :id, :name, include_blank: true, class: "col-sm-4") %>
</div>

<div class="row">
    <%= f.label :email_primary, class: "col-sm-2" %>
    <%= f.email_field :email_primary, class: "col-sm-4" %>
    
    <%= f.label :email_secondary, class: "col-sm-2" %>
    <%= f.email_field :email_secondary, class: "col-sm-4" %>
</div>

<div class="row">
    <%= f.label :work_phone, class: "col-sm-2" %>
    <%= f.phone_field :work_phone, class: "col-sm-4" %>
</div>

<div class="row">
    <%= f.label :subject_area, class: "col-sm-2" %>
    <div class="col-sm-4">
        <%= f.select :subject_area, ['Not Specified','Administration','English','Foreign Language','Generalist','History/Social Studies','Humanities','Math','Music','Performing Arts','Physical Education','Science','Technology','Theology','Visual Arts','Other'] %>
    </div>
    <%= f.label :other_subject, class: "col-sm-2"%>
    <%= f.text_field :other_subject, class: "col-sm-4" %>
</div>

<label> Teaches </label class="control-label col-sm-5">
<div class="row">
    <div class="form-group col-sm-6">
        <% all_grades = [:gPK, :gK, :g01, :g02, :g03, :g04, :g05, :g06, :g07, :g08, :g09, :g10, :g11, :g12] %>
        <% all_grades.each do |g| %>
            <%= f.label @contact.grade_field_label(g), class: "col-xs-5 col-sm-5"%>
            <%= f.check_box g, class: "col-xs-1 col-sm-1 col-sm-offset-1" %>
        <% end %>
    </div>
    <%= f.label :notes, class: "col-sm-2" %>
    <%= f.text_area :notes, class: "col-sm-4", rows: 6 %>
</div>

batdc/app/views/contacts/edit.html.erb
<%= form_for @contact, method: :patch do |f| %>
    <%= render 'contact', :f => f%>
    <div class="container">
        <div class ="row">
            <% btn_html = "btn btn-default col-xs-2 col-sm-2 col-md-2" %>
            <%= f.submit "Apply", class:  btn_html %>
            <%= button_tag "Reset", :type => 'reset', class: btn_html %>
            <%= button_to "Cancel", @contact, class: btn_html %>
        </div>
    </div>
<% end %>

batdc/app/views/contacts/email.html.erb
<div class="row">
    <%= form_tag(email_contacts_path, :method => "get", role: "search", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], class: "form-control col-md-4 col-sm-4 col-xs-6", placeholder: "Search Contacts" %>
    <% end %>
</div>

<% all_addrs = [] %>
<% @contacts.each do |c| %>    
    <% all_addrs << c.email_primary %>
<% end %>

<% if all_addrs.length <= 100 %>
    <%= mail_to all_addrs.join(','), 'Send Message' %>
<% end %>

<% all_addrs.each do |a| %>    
    <div><%= a %></div>
<% end %>

batdc/app/views/contacts/index.html.erb
<div class="container">
  <div class="row col-xs-12 col-sm-12 col-md-12">
    <% hidden_scopes = [:role, :is_function, :is_preferred, :at_member, :subject] %>
    <%= form_tag(contacts_path, :method => "get", role: "search", id: "search-form") do %>
      <div class="input-group">
        <span class="input-group-addon" id="status">
          <%= label_tag(:status, "All") %>
          <%= check_box_tag(:show_inactive, params[:show_inactive], params[:show_inactive], :onchange=>"this.form.submit();") %>
        </span>
        <% regions = ['Bay Area', 'Southern California', 'Other']%>
        <%= select_tag(:in_region, options_for_select(regions, params[:in_region]), class: "form-control", :onchange => "this.form.submit();", :include_blank => true) %>
        <span class="input-group-addon" id="sizing-addon1">Region</span>
      </div>
      <div class="input-group">
        <% if not params[:in_region].blank? %>
          <%= select_tag(:at_school, options_from_collection_for_select(School.region(params[:in_region]), :id, :name, params[:at_school]), class: "form-control", :onchange => "this.form.submit();", :include_blank => true) %>
        <% else %>
          <%= select_tag(:at_school, options_from_collection_for_select(School.all, :id, :name, params[:at_school]), class: "form-control", :onchange => "this.form.submit();", :include_blank => true) %>
        <% end %>
        <span class="input-group-addon" id="school-addon1">School</span>
      </div>
      <%= search_field_tag :search, params[:search], class: "form-control hasclear col-md-12 col-sm-12 col-xs-12", placeholder: "Search Contacts" %>

      <% hidden_scopes.each do |s| %>
        <% if not params[s].blank? %>
          <%= hidden_field_tag s, params[s] %>
        <% end %>
      <% end %>
      
      <% if params[:teaches] %>
        <% params[:teaches].each do |g| %>
          <%= hidden_field_tag 'teaches[]', g %>
        <% end %>
      <% end %>
    <% end %>
    
    <%= button_to('New', new_contact_path(), method: :get, class: "btn btn-default col-md-2 col-sm-2 col-xs-2") %>
    
    <% all_scopes = hidden_scopes + [:search, :at_school, :in_region] %>
    <% search_params = {} %>
    <% all_scopes.each do |s| %>
      <% if params[s] and not params[s].blank? %>
        <% search_params[s] = params[s] %>
      <% end %>
    <% end %>
    
    <%= link_to('Email', email_contacts_path(search_params), method: :get, class: "btn btn-default col-md-2 col-sm-2 col-xs-2") %>
    <%= link_to('Export', contacts_path(search_params.merge(format: :csv) ), method: :get, class: "btn btn-default col-md-2 col-sm-2 col-xs-2") %>
  </div>
</div>

<table class="span-12 col-xs-12 col-sm-12 col-md-12">
<tr>
<th>Name</th>
<th>Email</th>
<th>Role</th>
<th>School</th>
</tr>
<% @contacts.each do |c| %>
<% name = c.sort_name %>
<tr>
<td><%= link_to name, c %></td>
<td><%= mail_to c.email_primary %></td>
<td><%= c.role %></td>
<% if c.school %>
    <td><%= link_to c.school.official_name, c.school %></td>
<% else %>
    <td> NOT SPECIFIED </td>
<% end %>
</tr>
<% end %>
</table>

<div class="span-12"
<%= will_paginate @contacts %>
</div>

batdc/app/views/contacts/new.html.erb
<%= form_for @contact, url: {action: "create"} do |f| %>
    <%= render 'contact', :f => f %>
    <% btn_html = "btn btn-default col-xs-2 col-sm-2 col-md-2" %>
    <%= f.submit "Create", class: btn_html %>
    <%= f.submit "Cancel", class: btn_html %>
<% end %>

batdc/app/views/contacts/show.html.erb
<h3> <%= @contact.first %> <%= @contact.last%> </h3>
<h4> <%= @contact.status %> </h4>
<table>
<tr><td>School</td><td>
    <% if @contact.school %>
      <%= link_to @contact.school.official_name, @contact.school %>
    <% else %>
        NOT SPECIFIED
    <% end %>
</td></tr>
<tr><td>Title</td><td><%= @contact.title %></td></tr>
<tr><td>Role</td><td><%= @contact.role %></td></tr>
<tr><td>Email</td><td><%= mail_to @contact.email_primary %></td></tr>
<% if @contact.email_secondary %>
    <tr><td>Email</td><td><%= @contact.email_secondary %></td></tr>
<% end %>
<tr><td>Phone</td><td><%= phone_number_link @contact.work_phone %></td></tr>
<tr><td>Subject Area</td><td><%= @contact.subject_area %></td></tr>
</table>

<h4>Notes:</h4>
<div><p>
<%= @contact.notes %>
</p></div>

<table>
<tr><th>Teaches:</th></tr>
<% @contact.grades_taught.each do |g| %>
<tr><td><%= g %></td></tr>
<% end %>
</table>

<table>
<tr><th>Attended:</th></tr>
<% @contact.events.each do |e| %>
<tr><td><%= link_to e.event_name, e %></td></tr>
<% end %>
</table>

<% btn_html = "btn btn-default col-xs-4 col-sm-2 col-md-2" %>
<%= button_to('Edit', edit_contact_path(@contact), method: :get, class: btn_html) %>
<%= button_to('Delete', @contact, method: :delete, class: btn_html, data: {confirm: 'Confirm?'} ) %>