batdc/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  
  devise_scope :user do
    root to: 'lists#index'    
    get 'access_denied' => 'users/registrations#access_denied', as: :access_denied
  end

  resources :users, :except => [:new, :create] do
    member do
      patch :authorize
    end
  end
 
  resources :contacts do
    collection do
      get :email
    end
  end

  resources :schools do
    member do
      patch :add_preferred
      patch :add_membership
      patch :del_membership
    end
  end
  resources :events do
    member do
      patch :add_attendee
      get :email
      get :export
    end
  end

  resources :attendees, only: [:destroy]
  resources :preferred_contacts, only: [:destroy]

  get 'lists/index' => 'lists#index'
  get 'lists/membership' => 'lists#membership'
end

batdc/app/models/school.rb
class School < ActiveRecord::Base
  has_many :contacts
  has_many :preferred_contacts
  has_many :membership_years
  has_many :attendees, foreign_key: :sponsor_school_id
  has_many :events, through: :attendees
  has_many :event_venues, :class_name => 'Event', :foreign_key => 'school_id'

  after_validation :geocode
  geocoded_by :full_address

  scope :search, -> (term) { 
    t = "%#{term}%"
    pred = "name like ? "
    pred += "or official_name like ? "
    where(pred, t, t)
  }

  scope :region, -> (region) { where(region: region) }

  scope :member_in, -> (year) {
    where id: MembershipYear.in_year(year).select(:school_id)
  }
  
  scope :current_member, -> {
    where id: MembershipYear.current.select(:school_id)
  }

  scope :non_member, -> {
    where.not id: MembershipYear.current.select(:school_id)
  }

  def full_address(commas=true)
    addr = "#{address1} #{address2}, #{city}, #{state}"
  end

  def map_link
    link_base = "https://www.google.com/maps/place/"
   
    addr_comps = full_address.split
    url = "#{link_base}#{addr_comps.join('+')}"
  end
  
  def geocode_if_needed
    geocode if latitude == nil
  end

  def sent_to_events
    self.attendees.includes(:contact).includes(:event).order("contacts.last, contacts.first")
  end

end

batdc/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  load_and_authorize_resource except: [:create]

  before_filter :check_for_mobile, :only => [:index]

  def index
    if params[:members_only] 
      @schools = School.joins(:membership_years).where('membership_years.year' => 2015)
    else
      @schools = School.all
    end

    @schools = @schools.search(params[:search]) unless params[:search].blank?     
    @schools = @schools.region(params[:region]) unless params[:region].blank?
    @schools = @schools.order(:name)
    @schools = @schools.paginate(page: params[:page]) unless params[:mobile]
  end

  def show
    @school.geocode_if_needed
  end

  def new
    @school = School.new
  end
  
  def create
    authorize! :create, School
    if params[:commit] == "Cancel"
      redirect_to School
    else
      @school = School.create(school_params)
      redirect_to @school
    end
  end

  def update
    if params[:commit] == "Cancel"
      redirect_to @school
    else
      if @school.update(school_params)
        redirect_to @school
      else
        render 'edit'
      end
    end
  end

  def destroy
    if @school.contacts.length > 0
      flash[:alert] = "Remove contacts before deleting:
    #{@school.name}"
      redirect_to @school
    elsif @school.membership_years.length > 0
      flash[:alert] = "Remove membership before deleting: #{@school.name}"
      redirect_to @school
    elsif @school.attendees.length > 0
      flash[:alert] = "Remove event attendance before deleting: #{@school.name}"
      redirect_to @school
    else
      @school.destroy
      flash[:notice] = "Deleted School: #{@school.name}"
      redirect_to School
    end
  end

  def add_preferred
    c_id = params[:preferred_contact][:contact_id]
    s_id = params[:id]
    pc = PreferredContact.create({school_id: s_id, contact_id: c_id})
    redirect_to edit_school_path(@school)
  end

  def add_membership    
    my = MembershipYear.create(school_id: params[:id], year:
    params[:year] )
    redirect_to edit_school_path(@school)
  end

  def del_membership
    MembershipYear.delete_all(["school_id = ? AND year = ?", params[:id], params[:year]])
    redirect_to edit_school_path(@school)
  end

  private
  def school_params
    params.require(:school).permit(:name, :official_name, :website,
  :office_phone, :fax, :address1, :address2, :city, :state, :zip,
  :country, :notes, :region, :prek, :elementary, :middle, :highschool,
                                   preferred_contacts_attributes: [
  :contact_id, :school_id, :year])
  end

end

batdc/app/views/schools/_membership.html.erb
<div class="row">
    <h4> Membership Years </h4>
    <table class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <% @school.membership_years.order(:year).each do |my| %>
            <%= form_tag(del_membership_school_path(@school), method: :patch, id: "del-#{my.year}") do %>
                <%= hidden_field_tag(:year, my.year) %>
                <tr>
                    <td><%= my.year %></td>
                    <td> <%= submit_tag('Delete', data: {confirm: "Confirm?"}) %></td>
                </tr>
            <% end %>
        <% end %>
    </table>
</div>

batdc/app/views/schools/_preferred.html.erb
<h4> Preferred Contacts: </h4>
<table class="col-xs-12 col-sm-12 col-md-12">
    <% @school.preferred_contacts.each do |pc| %>
      <% if pc.contact %>
        <tr>
          <td><%= link_to pc.contact.full_name, pc.contact %></td>
          <td><%= pc.contact.role %></td>
          <td><%= pc.contact.work_phone %></td>
          <td><%= pc.contact.email_primary %></td>
          <% if :editing %>
            <td>
              <%= button_to 'Delete', pc, method: :delete, data: {confirm: "Confirm?"} %>
            </td>         
          <% end %>
        </tr>
      <% end %>
    <% end %>
</table>

batdc/app/views/schools/_school.html.erb
<div class="form-group">
    <div class="row">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <%= f.text_field :name, class: "col-sm-4" %>

        <%= f.label :official_name, class: "col-sm-2 control-label" %>
        <%= f.text_field :official_name, class: "col-sm-4" %>
    </div>
    <div class="row">
        <%= f.label :website, class: "col-sm-2 control-label" %>
        <%= f.text_field :website, class: "col-sm-10" %>
    </div>
    <div class="row">
        <%= f.label :office_phone, class: "col-sm-2 control-label" %>
        <%= f.phone_field :office_phone, class: "col-sm-4" %>
        
        <%= f.label :fax, class: "col-sm-2 control-label" %>
        <%= f.phone_field :fax, class: "col-sm-4" %>
    </div>

    <div class="row">
        <%= f.label :address1, class: "col-sm-2 control-label" %>
        <%= f.text_field :address1, class: "col-sm-4" %>
        
        <%= f.label :address2, class: "col-sm-2 control-label" %>
        <%= f.text_field :address2, class: "col-sm-4" %>
    </div>

    <div class="row">
        <%= f.label :city, class: "col-sm-2 control-label" %>
        <%= f.text_field :city, class: "col-sm-4" %>

        <%= f.label :state, class: "col-sm-2 control-label" %>
        <%= f.text_field :state, class: "col-sm-1" %>
        
        <%= f.label :zip, class: "col-sm-1 control-label" %>
        <%= f.text_field :zip, class: "col-sm-2" %>
    </div>

    <div class="row">
        <%= f.label :region, class: "col-sm-2 control-label" %>
        <%= f.select :region, ['Bay Area','Southern California','Other'], class: "col-sm-2" %>
    </div>
</div>

<% categories = [:prek, :elementary, :middle, :highschool] %>
<% labels = { :prek => 'Pre-K',
              :elementary => 'Elementary',
              :middle => 'Middle',
              :highschool => 'High School'} %>
 
<div class="form-group col-sm-4" rows="<%= categories.length %>">
    <% categories.each do |c| %>
        <div class="row">
            <label class="control-label col-sm-5"> <%= labels[c] %></label>
            <%= f.check_box c, class: "col-sm-1" %>
        </div>
    <% end %>
</div>

<div class="form-group col-sm-8">
    <%= f.label :notes, class: "col-sm-2 control-label" %>
    <%= f.text_area :notes, class: "col-sm-6", rows: 4 %>
</div>

batdc/app/views/schools/edit.html.erb
<%= simple_form_for @school, method: :patch do |f| %>
    <div class="form-inputs">
        <%= render 'school', :f => f%>

        <div class ="container">
            <div class="row">
                <%= f.submit "Apply", class:  "col-sm-2" %>
                <%= button_tag "Reset", :type => 'reset', class: "col-sm-2" %>
                <%= button_to "Cancel", @school, class: "col-sm-2" %>
            </div>
        </div>
    </div>
<% end %>

<%= render 'preferred', locals: {editing: true} %>

<%= form_tag(add_preferred_school_path(@school), :method => "patch", id: "pref-form") do %>
    <div class="form-inputs">
        <%= label_tag('Add Preferred Contact') %>
        <%= collection_select(:preferred_contact, :contact_id, @school.contacts.order(:last, :first), :id, :role_and_name) %>
        <%= submit_tag('Add') %>
    </div>
<% end %>

<%= render 'membership', locals: {editing: true} %>
<%= form_tag(add_membership_school_path(@school), :method => "patch", id: "pref-form") do %>
    <div class="form-inputs">
        <%= label_tag('Add Membership Year') %>
        <%= number_field_tag(:year) %>
        <%= submit_tag('Add') %>
    </div>
<% end %>

batdc/app/views/schools/index.html.erb
<div class="row col-xs-12 col-sm-12 col-md-12">
    <%= form_tag(schools_path, :method => "get", role: "search", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], class: "form-control  col-md-4 col-sm-4 col-xs-6", placeholder: "Search Schools" %>
        <% regions = ['Bay Area', 'Southern California', 'Other']%>
        <%= select_tag(:region, options_for_select(regions, params[:region]), class: "form-control col-md-4 col-sm-4 col-xs-6", :onchange => "this.form.submit();", :include_blank => true) %>
        <%= label_tag(:members_only, "Member Schools Only") %>
        <%= check_box_tag(:members_only, params[:members_only], params[:members_only], :onchange=>"this.form.submit();") %>

    <% end %>
</div>

<div class="row col-xs-12 col-sm-12 col-md-12">
<%= button_to('New', new_school_path(), method: :get, class: "btn btn-default col-xs-2 col-sm-2 col-md-2") %>
</div>

<div class="row col-xs-12 col-sm-12 col-md-12">
<table class="col-sm-12 col-md-12">
<tr>
<th>Name</th>
<th>Web</th>
<th>Phone</th>
<th>City</th>
</tr>
<% @schools.each do |s| %>
<tr>
<% name_or_blank = (s.name and s.name.length > 0) ? s.name : 'BLANK'%>
<td><%= link_to name_or_blank, s %></td>
<% if s.website %>
    <td><%= link_to 'web', s.website %> </td>
<% else %>
    <td> </td>
<% end %>
<td><%= s.office_phone %></td>
<td><%= s.city %></td>
</tr>
<% end %>
</table>
</div>
<%= will_paginate @schools %>

batdc/app/views/schools/new.html.erb
<%= form_for @school, url: schools_path do |f| %>
    <%= render 'school', :f => f%>
    <% btn_html = "btn btn-default col-xs-2 col-sm-2 col-md-2" %>
    <%= f.submit "Create", class: btn_html %>
    <%= f.submit "Cancel", class: btn_html %>
<% end %>

batdc/app/views/schools/show.html.erb
<h3> <%= @school.official_name %> </h3>
<h4> <%= phone_number_link @school.office_phone %> </h4>
<div class="row">
    <table class="col-sm-4 col-xs-8">
        <tr><th>Address</th></tr>
        <tr><td><%= @school.address1 %></td></tr>
        <tr><td><%= @school.address2 %></td></tr>
        <tr><td><%= @school.city %></td></tr>
        <tr><td><%= @school.state %></td></tr>
        <tr><td><%= @school.zip %></td></tr>
        <tr><td><%= @school.country %></td></tr>
    </table>

    <style>
     #map_canvas {
         width: 250px;
         height: 200px;
     }
    </style>      
    <script src="https://maps.googleapis.com/maps/api/js?callback=initialize"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
    <script> 
     google.maps.event.addDomListener(window, 'load', initialize);
     google.maps.event.addDomListener(window, 'page:load', initialize);

     function initialize() {
         var s_loc = new google.maps.LatLng(<%= @school.latitude %>, <%= @school.longitude %>);
         var map_canvas = document.getElementById('map_canvas');
         var map_options = {
             center: s_loc,
             zoom: 12,
             mapTypeId: google.maps.MapTypeId.ROADMAP
         };
         
         themap = new google.maps.Map(map_canvas, map_options);
         var marker = new google.maps.Marker({
             position: s_loc,
             map: themap,
             url: "<%= @school.map_link %>",
             title: "<%= @school.name %>"
         });
         
         google.maps.event.addListener(marker, 'click', function() {
             window.location.href = marker.url;
         });
     }
     
     $(document).ready( initialize );
     $(document).on("page:load", initialize );
    
    </script>
    <div id="map_canvas" class="col-sm-4 col-xs-8"></div>
</div>

<% levels = [] %>
<% levels << "Pre-K" if @school.prek %>
<% levels << "Elementary" if @school.elementary %>
<% levels << "Middle School" if @school.middle %>
<% levels << "High School" if @school.highschool %>
<table>
    <tr><th>Levels</th></tr>
    <% levels.each do |l| %>
        <tr><td><%= l %></td></tr>
    <% end %>
</table>

<h4>Notes:</h4>
<div><p>
<%= @school.notes %>
</p></div>

<%= render 'preferred' %>

<h4> Member In: </h4>
<div class="row">
<% @school.membership_years.order(year: :desc).each do |y| %>
    <div class="col-xs-2 col-sm-1 col-md-1"><%= y.year %></div>
<% end  %>
</div>


<h4>Event Participation:</h4>
<table class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<% @school.sent_to_events.each do |a| %>
    <tr>
        <td><%= link_to a.contact.full_name, a.contact %></td>
        <td><%= link_to a.event.event_name, a.event %></td>
    </tr>
<% end %>
</table>

<% btn_html = "btn btn-default col-xs-4 col-sm-2 col-md-2" %>
<%= button_to('Edit', edit_school_path(@school), method: :get, class: btn_html) %>
<%= button_to('Delete', @school, method: :delete, class: btn_html, data: {confirm: 'Confirm?'} ) %>