batdc/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  
  devise_scope :user do
    root to: 'lists#index'    
    get 'access_denied' => 'users/registrations#access_denied', as: :access_denied
  end

  resources :users, :except => [:new, :create] do
    member do
      patch :authorize
    end
  end
 
  resources :contacts do
    collection do
      get :email
    end
  end

  resources :schools do
    member do
      patch :add_preferred
      patch :add_membership
      patch :del_membership
    end
  end
  resources :events do
    member do
      patch :add_attendee
      get :email
      get :export
    end
  end

  resources :attendees, only: [:destroy]
  resources :preferred_contacts, only: [:destroy]

  get 'lists/index' => 'lists#index'
  get 'lists/membership' => 'lists#membership'
end

batdc/app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendees
  has_many :contacts, through: :attendees
  belongs_to :school

  scope :search, -> (term) {
    t = "%#{term}%"
    pred = "event_name like ?"
    where(pred, t)
  }

  scope :region, -> (region) {
    joins(:school).where('schools.region' => region)
  }

  scope :in_fiscal_year, -> (year) {
    fy_start = "#{year.to_i-1}-07-01".to_date
    fy_end = "#{year}-06-30".to_date
    where("start_date > ? AND start_date <= ?", fy_start, fy_end)
  }

  def attendance
    attendees.count
  end

  def schools_participating
    attendees.select(:sponsor_school_id).uniq.count
  end
  
  def region
    return "" unless school
    abbrev = {
      'Bay Area' => 'SF',
      'Southern California' => 'LA',
      'Other' => 'Other'
    }
    school.region ? abbrev[school.region] : ""
  end
end

batdc/app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource except: [:create]

  before_filter :check_for_mobile, :only => [:index, :show]

  def index
    @events = Event.all
    @events = @events.in_fiscal_year(params[:fiscal_year]) unless params[:fiscal_year].blank?
    @events = @events.search(params[:search]) unless params[:search].blank?
    @events = @events.region(params[:region]) unless params[:region].blank?
    @events = @events.order(start_date: :desc)

    respond_to do | format |
      format.html {
        @events = @events.paginate(page: params[:page]) unless params[:mobile]
      }

      format.csv {
        render csv: @events, filename: 'events',
        each_serializer: EventSerializer, only: [:event_name,
        :start_date, :end_date, :school, :url],
        add_methods: [:attendance, :schools_participating, :region]
      }
    end
  end

  def create
    authorize! :create, Event
    if params[:commit] == "Cancel"
      redirect_to Event
    else
      @event = Event.create(event_params)
      redirect_to @event
    end
  end

  def update
    if params[:commit] == "Cancel"
      redirect_to @event
    else
      if @event.update(event_params)
        redirect_to @event
      else
        render 'edit'
      end
    end
  end

  def add_attendee
    a = Attendee.create( contact_id: params[:attendee][:contact_id],
                          event_id: @event.id,
                          sponsor_school_id: params[:attendee][:sponsor_school_id],
                          paid: params[:paid] )
    redirect_to edit_event_path(@event)
  end
  
  def email    
  end

  def export
    respond_to do | format |
      format.csv { render csv: @event.contacts, filename: @event.event_name,
    each_serializer: ContactSerializer, only: [ :last, :first, :role,
    :title, :work_phone], add_methods: [:school_name, :email,
    :subject] }
      format.json { render json: @event.contacts,
    each_serializer: ContactSerializer }
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "Deleted Event: #{@event.event_name}"
    redirect_to Event
  end

  private
  def event_params
    params.require(:event).permit(:eventbrite_id, :event_name,
  :event_type, :series, :start_date, :end_date, :school_id, :url,
  :description, :notes, :num_sessions)
  end

end

batdc/app/helpers/events_helper.rb
module EventsHelper
end

batdc/app/views/events/.#_attendee.html.erb
kmoore@server.local.43060

batdc/app/views/events/_attendee.html.erb
<div class="container-fluid">
    <h4> Attendees </h4>
    <table class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <th>Contact</th>
        <th>Sponsor School</th>
        <th>Paid</th>
        <% @event.attendees.each do |a| %>
            <tr>
                <td><%= a.contact ? a.contact.full_name : 'Contact Not Found' %></td>
                <td><%= a.sponsor_school ? a.sponsor_school.name : 'None Specified' %></td>
                <td><%= a.paid %></td>
                <% btn_html = "btn btn-default" %>
                <td> <%= button_to 'Delete', a, method: :delete, data: {confirm: "Confirm?"}, class: btn_html %></td>
            </tr>
        <% end %>
    </table>
</div>

batdc/app/views/events/_event.html.erb
<div class="container-fluid"
    <div class="row">
        <%= f.label :event_name, class: "col-sm-2" %>
        <%= f.text_field :event_name, class: "col-sm-4" %>
        
        <%= f.label :series, class: "col-sm-2" %>
        <%= f.text_field :series, class: "col-sm-4" %>    
        
        <%= f.label :eventbrite_id, class: "col-sm-2" %>
        <%= f.number_field :eventbrite_id, class: "col-sm-4" %>
        
        <%= f.label :venue, class: "col-sm-1"%>
        <%= collection_select(:event, :school_id, School.all.order(:name), :id, :name, include_blank: true, class: "col-sm-5") %>
    </div>
    
    <div class="row">
        <%= f.label :start_date, class: "col-sm-2 col-xs-4" %>
        <%= f.date_field :start_date, class: "col-sm-4 col-xs-8"%>
        
        <%= f.label :end_date, class: "col-sm-2 col-xs-4" %>
        <%= f.date_field :end_date, class: "col-sm-4 col-xs-8"%>
    </div>
    
    <div class="row">
        <%= f.label :url, class: "col-sm-2" %>
        <%= f.text_field :url, class: "col-sm-4" %>

        <%= f.label :num_sessions, class: "col-sm-2" %>
        <%= f.number_field :num_sessions, class: "col-sm-4" %>    
    </div>
    <div class="row">
            
        <div class="row">
            <%= f.label :description, class: "col-sm-2 col-xs-4" %>
            <%= f.text_area :description, class: "col-sm-4 col-xs-8", rows: 6 %>
            
            <%= f.label :notes, class: "col-sm-2 col-xs-4" %>
            <%= f.text_area :notes, class: "col-sm-4 col-xs-8", rows: 6 %>
        </div>
    </div>
</div>

batdc/app/views/events/edit.html.erb
<%= form_for @event, method: :patch do |f| %>
    <%= render 'event', :f => f%>
    <div class="container">
        <div class ="row">
            <% btn_html = "btn btn-default col-xs-2 col-sm-2 col-md-2" %>
            <%= f.submit "Apply", class: btn_html %>
            <%= button_tag "Reset", :type => 'reset', class:  btn_html %>
            <%= button_to "Cancel", @event, class: btn_html %>
        </div>
    </div>
<% end %>

<div class="container-fluid">
    <h4> Attendees </h4>
    <%= render 'attendee' %>

    <%= form_tag(add_attendee_event_path(@event), :method => "patch", id: "attendee-form") do %>
        <div class="form-inputs">
            <%= label_tag('Add Attendee') %>
            <%= collection_select(:attendee, :contact_id, Contact.status('Active').order(:last, :first), :id, :sort_name) %>
            <%= collection_select(:attendee, :sponsor_school_id, School.all.order(:name), :id, :name, include_blank: true) %>
            <%= label_tag(:paid) %>
            <%= number_field_tag(:paid, :paid)%>
            <%= submit_tag('Add', class: "btn btn-default") %>
        </div>
    <% end %>
</div>

batdc/app/views/events/email.html.erb
<% all_addrs = [] %>

<% @event.attendees.includes(:contact).each do |a| %>
    <% if a.contact %>
        <% all_addrs << a.contact.email_primary %>
    <% end %>
<% end %>

<% if all_addrs.length <= 100 %>
    <%= mail_to all_addrs.join(','), 'Send Message' %>
<% end %>

<% all_addrs.each do |addr| %>
    <div><%= addr %></div>   
<% end %>

batdc/app/views/events/index.html.erb
<div class="row col-xs-12 col-sm-12 col-md-12">
    <%= form_tag(events_path, :method => "get", role: "search", id: "search-form") do %>
        <%= text_field_tag :search, params[:search],
        class: "form-control col-md-4 col-sm-4 col-xs-6",
            placeholder: "Search Events" %>
        <%= select_tag(:region,
                       options_for_select(['Bay Area','Southern California','Other'], params[:region]),
                       include_blank: true,  :onchange => "this.form.submit();",
                       class: "form-control col-md-4 col-sm-4 col-xs-6") %>
    <% end %>
</div>

<% all_scopes = [:search, :region, :fiscal_year] %>
<% search_params = {} %>
<% all_scopes.each do |s| %>
    <% if params[s] and not params[s].blank? %>
        <% search_params[s] = params[s] %>
    <% end %>
<% end %>

<%= button_to('New', new_event_path, method: :get, class: "btn btn-default col-md-2 col-sm-2 col-xs-2") %>
<%= link_to('Export', events_path(search_params.merge(format: :csv)), class: "btn btn-default col-md-2 col-sm-2 col-xs-2") %>

<table class="col-xs-12 col-sm-12 col-md-12">
    <tr>
        <th>Region</th>
        <th>Name</th>
        <th>Start</th>
        <th class="text-right">Count</th>
        <th class="text-right">Total</th>
    </tr>
    <% @events.each do |e| %>
        <tr>
            <td><%= e.region %></td>
            <td><%= link_to e.event_name, e %></td>
            <td><%= e.start_date.strftime("%m/%d/%Y") %></td>
            <td class="text-right"><%= e.attendees.count %></td>
            <td class="text-right"><%= number_to_currency(e.attendees.sum(:paid)) %></td>
        </tr>
    <% end %>
</table>

<div class ="row col-xs-12 col-sm-12 col-md-12">
<%= will_paginate @events %>
</div>

batdc/app/views/events/new.html.erb
<%= form_for @event, url: {action: "create"} do |f| %>
    <%= render 'event', :f => f %>
    <% btn_html = "btn btn-default col-xs-2 col-sm-2 col-md-2" %>
    <%= f.submit "Create", class: btn_html %>
    <%= f.submit "Cancel", class: btn_html %>
<% end %>

batdc/app/views/events/show.html.erb
<h3> <%= @event.event_name %> </h3>
<h4><%= @event.series %></h4>
<div class="row">
    <div class="col-sm-2 col-xs-4"> Start </div>
    <div class="col-sm-4 col-xs-8"><%= @event.start_date %></div>
    <div class="col-sm-2 col-xs-4"> End </div>
    <div class="col-sm-4 col-xs-8"><%= @event.end_date %></div>
</div>

<div class="row">
    <% if @event.eventbrite_id %>
        <div class="col-sm-2 col-xs-4"> Eventbrite </div>
        <% dash_url = "https://www.eventbrite.com/myevent?eid=#{@event.eventbrite_id}" %>
        <div class="col-sm-2 col-xs-4"><%= link_to @event.eventbrite_id, dash_url %></div>
    <% else %>
        <%= link_to 'url', @event.url %>
    <% end %>
</div>

<% if @event.school %>
    <div class="row">
        <%= @event.school.official_name %>
    </div>
<% end %>

<% if @event.num_sessions %>
    <p> <%= @event.num_sessions %> Sessions </p>
<% end %>

<h4>Notes:</h4>
<%= @event.notes %>

<h4>Attendees: <%= @event.attendees.count %></h4>
<table class="col-xs-12 col-sm-12 col-md-12">
    <th>Name</th>
    <th>Email</th>
    <th>School</th>
    <th>Paid</th>
    <% atts = @event.attendees.includes(:contact, :sponsor_school).sort { |a, b| a.sort_name <=> b.sort_name }%>
    <% atts.each do |a| %>
        <tr>
            <% if a.contact %>
                <td> <%= link_to a.contact.full_name, a.contact %> </td>
                <td> <%= a.contact.email_primary %> </td>
            <% else %>
                <td> CONTACT NOT FOUND </td>
                <td> ID <%= a.contact_id %> </td>
            <% end %>
            <% if a.sponsor_school %>
                <td> <%= link_to a.sponsor_school.name, a.sponsor_school %> </td>
            <% else %>
                <td> NOT SPECIFIED </td>
            <% end %>
            <td> <%= number_to_currency(a.paid) %> </td>
        </tr>
    <% end %>
    <tr><td></td>
        <td></td>
        <td></td>
        <th><%= number_to_currency(@event.attendees.sum(:paid)) %></th>
    </tr>
</table>
<% btn_html = "btn btn-default col-xs-2 col-sm-2 col-md-2" %>
<%= button_to('Edit', edit_event_path(@event), method: :get, class: btn_html ) %>
<%= button_to('Email', email_event_path(@event), method: :get, class: btn_html ) %>
<%= button_to('Export', export_event_path(@event, format: :csv), method: :get, class: btn_html ) %>
<%= button_to('Delete', @event, method: :delete, class: btn_html, data: {confirm: 'Confirm?'} ) %>