batdc/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  
  devise_scope :user do
    root to: 'lists#index'    
    get 'access_denied' => 'users/registrations#access_denied', as: :access_denied
  end

  resources :users, :except => [:new, :create] do
    member do
      patch :authorize
    end
  end
 
  resources :contacts do
    collection do
      get :email
    end
  end

  resources :schools do
    member do
      patch :add_preferred
      patch :add_membership
      patch :del_membership
    end
  end
  resources :events do
    member do
      patch :add_attendee
      get :email
      get :export
    end
  end

  resources :attendees, only: [:destroy]
  resources :preferred_contacts, only: [:destroy]

  get 'lists/index' => 'lists#index'
  get 'lists/membership' => 'lists#membership'
end

batdc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <meta name="viewport" content="width=device-width">
    <head>
        <title>BATDC</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= favicon_link_tag 'favicon.ico' %>
    </head>
    <body>

        
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <div id="main-container" class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <%= link_to '/', class: 'navbar-logo' do %>
                            <%= image_tag "BATDC_Logo.png", :class => "navbar-logo" %>
                        <% end %>                        
                    </div>


                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
                            <li><%= link_to 'Schools', schools_path %></li>
                            <li><%= link_to 'Contacts', contacts_path %></li>
                            <li><%= link_to 'Events', events_path %></li>
                            <li><%= link_to 'Lists', lists_index_path %></li>
                            <% if user_signed_in? and can? :manage, :all %>
                                <li><%= link_to 'Admin', users_path %></li>
                            <% end %>
                        </ul>
                       
                        <ul class="nav navbar-nav navbar-right">
                            <% if user_signed_in? %>                                
                                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                            <% else %>
                                <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
                            <% end %>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

            <%= yield %>
            
    </body>
</html>